### ISSUE TITLE
Improve Look and Feel of the Stop Pane

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#1]
## Current State

The stop pane is the overlay depicted in the bottom left corner of the screenshot. It currently looks like the following screenshot:

<img width="1155" alt="image" src="https://github.com/OneBusAway/onebusaway-webapp/assets/2254/cd7ba126-ec8e-479b-a41a-c6c3c6b86f25">

## Desired State

and we should reformat the data into something that looks more like the iOS app's arrivals and departures table:

![image](https://github.com/OneBusAway/onebusaway-webapp/assets/2254/82a3c6cc-5f58-43ae-9225-3b18cd8aeff5)

### ArrivalDeparture Component

![image](https://github.com/OneBusAway/onebusaway-webapp/assets/2254/d8a1d9ca-332d-4344-a411-0e0a8aae2e5e)

## Requirements

All of the necessary data has already been loaded in the component via its arrivals-and-departures API call. We can skip the pagination/load more feature for now. The only thing we need to focus on for the moment is improving the look and feel of StopPane.svelte

## Acceptance criteria

- [x] Remove the textarea containing JSON.stringify() information (it's a placeholder for debugging purposes)
- [x] Create a new ArrivalDeparture component that resembles the iOS screenshot in the _ArrivalDeparture Component_ section above
- [x] Render a list of ArrivalDeparture components from the data loaded from the server and display them in StopPane.

**Comment by aaronbrethorst** [comment]
@tarunsinghofficial a quick note for you: I may have given you the wrong impression about the styling of the stop pane. the screenshot I shared before was from the iOS app in dark mode. Here's what it looks like in light mode. the stop pane here should behave similarly. 

![IMG_507AB50CCE5A-1](https://github.com/OneBusAway/onebusaway-webapp/assets/2254/bcb87418-a774-4d97-b0dc-fdb78d6b9c8c)

We'll add proper support for dark mode in #5, though

**Comment by tarunsinghofficial** [comment]
> @tarunsinghofficial a quick note for you: I may have given you the wrong impression about the styling of the stop pane. the screenshot I shared before was from the iOS app in dark mode. Here's what it looks like in light mode. the stop pane here should behave similarly.
> 
> ![IMG_507AB50CCE5A-1](https://private-user-images.githubusercontent.com/2254/341996489-bcb87418-a774-4d97-b0dc-fdb78d6b9c8c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTAwMTQsIm5iZiI6MTcxOTEwOTcxNCwicGF0aCI6Ii8yMjU0LzM0MTk5NjQ4OS1iY2I4NzQxOC1hNzc0LTRkOTctYjBkYy1mZGI3OGQ2YjljOGMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAyMjgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZDczNjc0MmJkNGE0MGY4ODcwNjMwYzQ4N2QyZTY4NDc3YjQ4ZTdjY2Y3ZjJkMDU4ZDM5NTJmYmMyMWRhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZmDtDPsICMF0hllpAIhRdIR8oUwe1E2nw6lWmqFcqE)
> 
> We'll add proper support for dark mode in #5, though

Okay, great! I will work on this.
