### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#27]
# User story

As a frequent transit rider,
I want to search for my favorite stops and routes,
so that I can quickly get to the information I need

# New Acceptance Criteria

- [x] Change search from typeahead to only submitting on pressing enter/return
- [x] The search pane should have a lower z-index than the stop modal

# Acceptance criteria

- [x] Add a new boolean value in the .env file for whether search is supported - search only works on OBA servers >= 2.2.2. https://developer.onebusaway.org/api/where/search
- [x] If search is disabled, nothing in the UI changes
- [x] If search is enabled, a search box is displayed in the navigation bar next to the logo
- [x] invoking search (by pressing return or enter) should cause a SearchResults component to appear within a ModalPane component.
- [x] A new OBA REST API proxy called `routes/api/oba/search` will be created that issues two API calls: one to the [Stop Search API](https://developer.onebusaway.org/api/where/search/stop) and one to the [Route Search API[(https://developer.onebusaway.org/api/where/search/route). It returns the results of both API calls in a structure that resembles the following: `{routeSearchResults, stopSearchResults}`
- [x] The search results component should issue an API request to the `routes/api/oba/search` API and display the results as two lists in the SearchResults component: Stops and Routes.
- [x] Clicking a Stop will center the map on the selected stop and open the StopPane with the expected results.
- [x] Clicking a Route will display: `alert("TODO: show route ${routeID}");`

**Comment by tarunsinghofficial** [comment]
@aaronbrethorst Can you show me a demo of how **search** works in iOS? That would be helpful for me to work on.
