### ISSUE TITLE
Add a 'Current Location' button to the map

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#4]
## User story

As a transit rider,
I want to easily see my current location on the map,
So that I can find nearby stops.

## Requirements

- [x] add a 'Find Current Location' button to the map using the [location-crosshairs](https://fontawesome.com/icons/location-crosshairs?f=classic&s=solid) icon. See StopPane.svelte for an example of how to use these. 
- [x] Clicking the button should prompt the user for permission to their location and, if granted, re-center the map on the user's location and show a dot on the map indicating the user's location.

## UI

The button should be located roughly where the purple box indicates.

<img width="415" alt="Screenshot 2024-06-22 at 9 05 44 AM" src="https://github.com/OneBusAway/onebusaway-webapp/assets/2254/de070730-ff8e-437f-b21a-7211c791e5c7">

**Comment by tarunsinghofficial** [comment]
I have done this task. PR is created.
