### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#5]
## User story

As a transit rider waiting for a bus at night,
I want the web app to respect my device's light/dark mode preferences,
so that my user experience is more pleasant.

## Requirements

- [x] Implement proper support for Dark Mode using Tailwind's `dark` variant: https://tailwindcss.com/docs/dark-mode
- [x] Implement proper support for Google Maps's Night Mode: https://developers.google.com/maps/documentation/javascript/examples/style-array
- [x] When my device is in light mode, I should see a light-styled UI
- [x] When my device is in dark mode, I should see a dark-styled UI

**Comment by tarunsinghofficial** [comment]
> ## User story
> As a transit rider waiting for a bus at night, I want the web app to respect my device's light/dark mode preferences, so that my user experience is more pleasant.
> 
> ## Requirements
> * [ ]  Implement proper support for Dark Mode using Tailwind's `dark` variant: https://tailwindcss.com/docs/dark-mode
> * [ ]  Implement proper support for Google Maps's Night Mode: https://developers.google.com/maps/documentation/javascript/examples/style-array
> * [ ]  When my device is in light mode, I should see a light-styled UI
> * [ ]  When my device is in dark mode, I should see a dark-styled UI

Great choice to add Dark Mode in the application. I will start working on this issue. Thanks
