### ISSUE TITLE
Route Search UI

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#56]
# Search Results

First, I search for a route, and then I click on it (e.g. the Route 10)

![Search results](https://github.com/user-attachments/assets/bdc02741-735b-4e2d-a521-086ac7a3e48c)

# Route Modal

Then, a modal pane appears from the bottom with the list of all stops in that route, and the route is displayed as a polyline on the map.

![Route Modal](https://github.com/user-attachments/assets/fe188429-8326-4632-9a91-86d8e131a347)

**Comment by Ahmedhossamdev** [comment]
#55
