### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-webapp#58]
# User Story

As a transit rider who does not speak English, 
I want to see the onebusaway-webapp UI automatically appear in my device's preferred language,
so that I can more effectively navigate transit.

# Acceptance Criteria

- [x] Evaluate and choose a tool for internationalization and localization (maybe this one? https://github.com/lokalise/i18n-ally)
- [x] Fully internationalize the product UI
- [x] Add support for another LTR language (Spanish, maybe?)

**Comment by tarunsinghofficial** [comment]
I'm also interested in working on this issue. Let me know If I can contribute. Thanks :)

**Comment by Ahmedhossamdev** [comment]
@tarunsinghofficial 

Cool! I’ve added a PR. If you have any better ideas, feel free to share them with me.

**Comment by Ahmedhossamdev** [comment]
#63

**Comment by aaronbrethorst** [comment]
Fixed in #63
